server:
  port: 8080
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DB_URL_DEV}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG
      springframework: DEBUG

    com:
      equipo01:
        featureflag: DEBUG
  